### ISSUE TITLE
iRODS 4.3 iCAT server occasionally hangs on container startup

### ISSUE THREAD

**Issue by mikkonie** [bihealth/irods-docker#30]
After upgrading to iRODS 4.3, I'm seeing a problem where one or both of the two iRODS iCAT servers I run hang and time out when starting up the containers in docker compose. I did not experience this in the v4.2 versions of this image.

[The 4.3 upgrade has been merged in the dev branch](https://github.com/bihealth/irods-docker/tree/dev).

[The docker-compose.yml used to launch the containers is here](https://github.com/bihealth/sodar-docker-compose/blob/upgrade-4.3/docker-compose.dev.yml).

When this happens, the iRODS server is in an unresponsive state. Local `iinit` as well as external connection attempts from the docker host time out. Other servers in the network (postgres and redis) are working ok and reachable. Docker compose output displays the following:

```
irods-1       | Start iRODS
irods-1       | Test iinit
irods-1       | remote addresses: 172.20.0.5 ERROR: _rcConnect: connectToRhost timed out, retrying
irods-1       | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
irods-1       | Enter your current iRODS password:
irods-1       | remote addresses: 172.20.0.5 ERROR: _rcConnect: connectToRhost error, server on irods:1247 is probably down status = -115000 SYS_SOCK_READ_TIMEDOUT
irods-1       | remote addresses: 172.20.0.5 ERROR: Saved password, but failed to connect to server irods
irods-1       | iinit failed
```

During this, running `/etc/init.d/irods status` in the container does display running iRODS processes, but curiously no `irodsDelayServer`:

```
root@irods:/# /etc/init.d/irods status
irodsServer :
  Process 477
  Process 478
  Process 492
```

SSH:ing into the container and doing `/etc/init.d/irods restart` makes the server work normally. Most of the time, restarting the container does the same.

I have not yet found a way to consistently reproduce this, as it occurs seemingly randomly. This seem to happen most often after rebuilding the image and starting it for the first time, but not exclusively.

iRODS log says the following:
```
 {"log_category":"server","log_level":"info","log_message":"Initializing server ...","server_host":"irods","server_pid":477,"server_timestamp":"2024-09-19T10:41:46.139Z","server_type":"server","server_zone":"sodarZone"}
 {"log_category":"server","log_level":"info","log_message":"Setting up UNIX domain socket for agent factory ...","server_host":"irods","server_pid":477,"server_timestamp":"2024-09-19T10:41:46.141Z","server_type":"server","server_zone":"sodarZone"}
 {"log_category":"server","log_level":"info","log_message":"Forking agent factory ...","server_host":"irods","server_pid":477,"server_timestamp":"2024-09-19T10:41:46.141Z","server_type":"server","server_zone":"sodarZone"}
 {"log_category":"server","log_level":"info","log_message":"Connecting to agent factory [agent_factory_pid=478] ...","server_host":"irods","server_pid":477,"server_timestamp":"2024-09-19T10:41:46.142Z","server_type":"server","server_zone":"sodarZone"}
 {"log_category":"agent_factory","log_level":"info","log_message":"Initializing agent factory ...","server_host":"irods","server_pid":478,"server_timestamp":"2024-09-19T10:41:46.143Z","server_type":"agent_factory","server_zone":"sodarZone"}
 {"local_hostname":"localhost, irods","log_category":"server","log_level":"info","port":"1247","server_host":"irods","server_pid":477,"server_timestamp":"2024-09-19T10:41:46.190Z","server_type":"server","server_zone":"sodarZone"}
 {"log_category":"server","log_level":"info","server_host":"irods","server_pid":477,"server_timestamp":"2024-09-19T10:41:46.206Z","server_type":"server","server_zone":"sodarZone","zone_info.host":"localhost","zone_info.name":"sodarZone","zone_info.port":"1247","zone_info.type":"LOCAL_ICAT"}
 {"log_category":"server","log_level":"info","log_message":"rodsServer Release version rods4.3.1 - API Version d is up","server_host":"irods","server_pid":477,"server_timestamp":"2024-09-19T10:41:46.207Z","server_type":"server","server_zone":"sodarZone"}
 {"log_category":"legacy","log_level":"info","log_message":">>> control plane :: listening on port 1248\n","server_host":"irods","server_pid":477,"server_timestamp":"2024-09-19T10:41:46.208Z","server_type":"server","server_zone":"sodarZone"}
 {"log_category":"server","log_level":"error","log_message":"readWorkerTask - readStartupPack failed. -4000","server_host":"irods","server_pid":477,"server_timestamp":"2024-09-19T10:41:48.177Z","server_type":"server","server_zone":"sodarZone"}
```

The last `readStartupPack failed` bit looks of interest. However, that line also seems to appear on successful startups?

### How to Reproduce

Start, stop and restart the docker compose environment 1-N times.

Oddly, this seems to happen on different intervals depending on the network I'm connected to when running the docker compose environment. However, I can't say for sure this isn't just a coincidence.

Also, I have **not** witnessed this happening when starting the image in GitHub Actions as part of [SODAR server CI](https://github.com/bihealth/sodar-server/blob/dev/.github/workflows/build.yml).

### Further Steps for Debugging

- ~~Upgrade from 4.3.1 to 4.3.3~~
    * Also happens on 4.3.3
- Enable debug logging in iRODS
- Search for reports of similar problems and solutions, especially regarding `irodsDelayServer`
    * Could not find anything that seems relevant
- If all else fails, contact iRODS support

**Comment by mikkonie** [comment]
This hasn't happened lately in dev, except occasionally after rebuilding the image. I'll keep looking into it and see if it also occurs in staging/production, but if not, I won't be considering this a blocker for v4.3.3-1.

**Comment by mikkonie** [comment]
Sadly, I have observed this also happening in staging after rebuilding the server. I should try to debug the issue with iRODS support. First, I should most likely enable trace logging and trigger the freeze-up.

**Comment by mikkonie** [comment]
[Minimal example for reproducing this here](https://github.com/mikkonie/docker-compose-irods-timeout). This seems to (mostly? exclusively?) affect rebuilding an existing image. Maybe some critical file is not correctly stored in volumes?

**Comment by trel** [comment]
Thinking this is due to the `.irodsA` file not being retained well enough for the server to come up cleanly after a restart of the container... 

the following diff appears to 'recreate' it and then the container stands up and appears to be ready.

```diff
$ git diff
diff --git a/docker/docker-entrypoint.sh b/docker/docker-entrypoint.sh
index d6da448..52a65dd 100755
--- a/docker/docker-entrypoint.sh
+++ b/docker/docker-entrypoint.sh
@@ -84,6 +84,14 @@ if [[ "$1" == "irods-start" ]]; then
 
     find /var/lib/irods -not -path '/var/lib/irods/Vault*' -exec chown $IRODS_SERVICE_ACCOUNT_GROUP:$IRODS_SERVICE_ACCOUNT_USER {} \;
 
+    # rebuild .irodsA after restart (workaround)
+    if [ -f /etc/irods/.provisioned ]; then
+        echo "'fixing' .irodsA"
+        set +e
+        su - irods -c "echo ${IRODS_ADMIN_PASS} | iinit"
+        set -e
+    fi
+
     # Start iRODS
     echo "Start iRODS"
     /etc/init.d/irods start
```

Will continue to find a better way to 'save' the `.irodsA` file cleanly enough not to require this 'fix' before starting the iRODS server.

**Comment by trel** [comment]
As an attempt to just 'save and restore' the `.irodsA` file...

```diff
$ git diff
diff --git a/docker/docker-entrypoint.sh b/docker/docker-entrypoint.sh
index 55e7790..da8e1bb 100755
--- a/docker/docker-entrypoint.sh
+++ b/docker/docker-entrypoint.sh
@@ -34,6 +34,12 @@ if [[ "$1" == "irods-start" ]]; then
             cp /etc/irods/irods_environment.json /var/lib/irods/.irods/irods_environment.json
         fi
 
+        if [ ! -f /var/lib/irods/.irods/.irodsA ]; then
+            mkdir -p /var/lib/irods/.irods
+            cp /etc/irods/.irodsA /var/lib/irods/.irods/.irodsA
+            chown -c $IRODS_SERVICE_ACCOUNT_GROUP:$IRODS_SERVICE_ACCOUNT_USER /var/lib/irods/.irods/.irodsA
+        fi
+
         if [ ! -f /var/lib/irods/.odbc.ini ]; then
             cp /etc/irods/.odbc.ini /var/lib/irods/.odbc.ini
         fi
@@ -69,6 +75,7 @@ if [[ "$1" == "irods-start" ]]; then
         echo "Perform iRODS setup"
         python3 /var/lib/irods/scripts/setup_irods.py --json_configuration_file=/unattended_config.json
 
+        cp /var/lib/irods/.irods/.irodsA /etc/irods/.irodsA
         cp /var/lib/irods/.irods/irods_environment.json /etc/irods/irods_environment.json
         cp /var/lib/irods/.odbc.ini /etc/irods/.odbc.ini
         cp -f /var/lib/irods/version.json /etc/irods/version.json
```

This is also not working... as the `.irodsA` file is designed not to be portable.

---

Instead for the current PR (#47)...
- On first run, `setup_irods.py` generates a good `.irodsA`.
- On container restart, regenerate `.irodsA` from the known password.

**Comment by trel** [comment]
Oh!  Adding `-p` to the two `cp` commands above... seems to have given the `.irodsA` enough consistent information to be good/usable.

The timestamp (mtime) matters.

So this is an alternative to #47.  Not sure which is best.  Feels a bit cleaner to just regenerate each time... fewer moving parts.


```diff
$ git diff
diff --git a/docker/docker-entrypoint.sh b/docker/docker-entrypoint.sh
index 55e7790..f56d02f 100755
--- a/docker/docker-entrypoint.sh
+++ b/docker/docker-entrypoint.sh
@@ -34,6 +34,12 @@ if [[ "$1" == "irods-start" ]]; then
             cp /etc/irods/irods_environment.json /var/lib/irods/.irods/irods_environment.json
         fi
 
+        if [ ! -f /var/lib/irods/.irods/.irodsA ]; then
+            mkdir -p /var/lib/irods/.irods
+            cp -p /etc/irods/.irodsA /var/lib/irods/.irods/.irodsA
+            chown -c $IRODS_SERVICE_ACCOUNT_GROUP:$IRODS_SERVICE_ACCOUNT_USER /var/lib/irods/.irods/.irodsA
+        fi
+
         if [ ! -f /var/lib/irods/.odbc.ini ]; then
             cp /etc/irods/.odbc.ini /var/lib/irods/.odbc.ini
         fi
@@ -69,6 +75,7 @@ if [[ "$1" == "irods-start" ]]; then
         echo "Perform iRODS setup"
         python3 /var/lib/irods/scripts/setup_irods.py --json_configuration_file=/unattended_config.json
 
+        cp -p /var/lib/irods/.irods/.irodsA /etc/irods/.irodsA
         cp /var/lib/irods/.irods/irods_environment.json /etc/irods/irods_environment.json
         cp /var/lib/irods/.odbc.ini /etc/irods/.odbc.ini
         cp -f /var/lib/irods/version.json /etc/irods/version.json
```

**Comment by mikkonie** [comment]
Oh, this is an excellent find, I will give it a go. Thank you so much for looking into it @trel!

**Comment by mikkonie** [comment]
Confirmed to be working and merged. Again, thank you a lot for helping out with this :) Closing the issue.

**Comment by trel** [comment]
Excellent.   Glad it works.
