### ISSUE TITLE
Increase default session timeout in iRODS v4.3.3

### ISSUE THREAD

**Issue by mikkonie** [bihealth/irods-docker#33]
After upgrading the image, the default login timeout seems to be VERY short. This should be altered. Not 100% sure if this should go here or sodar-docker-compose, will move if needed.

**Edit:** Instead of simply increasing the default maximum values, we should make them configurable by env vars.

**Comment by holtgrewe** [comment]
Is this login timeout with irods icommands? IIRC, this is goverend by PAM.

**Comment by mikkonie** [comment]
There are infact two settings for maximum login length. There is a separate one for PAM, yes. For some reason, one of these was set very short in my iRODS 4.3 unattended config template.

**Comment by mikkonie** [comment]
These settings have changed in 4.3.1+, [see here](https://docs.irods.org/4.3.1/system_overview/configuration/#authentication-configuration).

**Comment by mikkonie** [comment]
iRODS support to the rescue: this is an undocumented feature in v4.3.1+, where one is supposed to use `password_min_time` instead of / in addition to `password_max_time`.
