### ISSUE TITLE
Incorrect values provided for service account environment in unattended config template

### ISSUE THREAD

**Issue by mikkonie** [bihealth/irods-docker#8]
I noticed that we set PAM auth and SSL for the service account environment if they are used for incoming connections.

Unless I'm mistaken, this is wrong: the (mostly) locally connecting default service account uses native login and SSL should not be necessary, right?

I'll verify this with our existing setup, but if I'm right I'll need to fix this asap.

**Comment by messersc** [comment]
I was wondering, too.

As far as I understand, you are correct and the native auth does not need SSL.

But why would it be harmful to have pam and SSL set-up already? Ideally, you would have the service user locally and remote users through PAM with LDAP.

**Comment by mikkonie** [comment]
> But why would it be harmful to have pam and SSL set-up already? Ideally, you would have the service user locally and remote users through PAM with LDAP.

That is exactly how it is done. This ticket is specifically about the service account environment, where the login should be native, not pam. AFAIK the SSL settings can still be there though.

I fixed this issue, won't close though until I've properly tested it together with #9.
